### ISSUE TITLE
More flexible naming of results

### ISSUE THREAD

**Issue by tcdewit** [MedPhysQC/Generic_OCR#2]
Currently the user is forced to name results of the form "OCR_%".   
Why not create a dictionary under params like this? This hides the unnessary "OCR_" prefix, e.g.:  

            "params": {
                "OCR": {
                    "Detector:prefix": "Detector", 
                    "Detector:type": "float", 
                    "Detector:xywh": "25;120;100;25", 
                    "Integral uniformity:suffix": "%", 
                    "Integral uniformity:type": "float", 
                    "Integral uniformity:xywh": "882;294;100;25", 
                    "Label:type": "string", 
                    "Label:xywh": "64;416;200;25" 
                },
                "channel": "avg", 
                "slicenr": -1
            }

**Comment by asch99** [comment]
I just remembered: to keep wad_admin simple, all params are expected to be a simple dictionary, not a nested dictionary. That makes displaying and modifying params in wad_admin/selectors easy. Also there is a separate info dictionary in the comments block of the config which is linked by dictionary key to the params.

While not impossible, and probably nicer too, it would need adjustments of wad_admin and of the format of  all config files.

**Comment by asch99** [comment]
Changes is WAD-QC now allow a more flexible way of defining params.
